development:
  bucket: fppis
  access_key_id: AKIAJS5LXFFIXGEZFL3A
  secret_access_key: 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
test:
  bucket: fppis
  access_key_id: AKIAJS5LXFFIXGEZFL3A
  secret_access_key: 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
production:
  bucket: fppis
  access_key_id: AKIAJS5LXFFIXGEZFL3A
  secret_access_key: 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